### ISSUE TITLE
Error parsing legal xpath

### ISSUE THREAD

**Issue by MPvHarmelen** [goto100/xpath#104]
When running the following code snippet (using node.js)

```js
xpath = require("xpath");

xpath.parse('//text()[..[true()]]')
```
I get this error:

```
<redacted>/node_modules/xpath/xpath.js:1278
                    throw new Error("XPath parse error");
                    ^

Error: XPath parse error
    at XPathParser.parse (<redacted>/node_modules/xpath/xpath.js:1278:27)
    at Object.parse (<redacted>/node_modules/xpath/xpath.js:4738:33)
    at Object.<anonymous> (<redacted>/mwe.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

It seems like adding a constraint to the parent selector causes a parsing error.

This xpath does not throw and error: `//text()[parent::*[true()]]` and neither does `//text()[..]`.

The problematic xpath works when used in an [xpath playground](https://xpath.playground.fontoxml.com/?xpath=%2F%2Ftext%28%29%5B..%5Btrue%28%29%5D%5D).

**Comment by JLRishe** [comment]
That is not a legal XPath 1.0 expression. You cannot place a predicate directly after an abbreviated self or parent step in XPath 1.0. [Explanation](https://stackoverflow.com/a/28070010/1945651)

The following is a valid alternative:

```
//text()[(..)[true()]]
```

However, I would question why you are trying to use that expression, if it's not purely used for example purposes. Both the `..` and the `[true()]` seem to be redundant.

**Comment by MPvHarmelen** [comment]
Thanks! I indeed tried to create a minimum working example and agree this is quite a weird query :)
