### ISSUE TITLE
Won't compile with --use-strict flag 

### ISSUE THREAD

**Issue by NoxHarmonium** [goto100/xpath#31]
When I use this module in my project which runs node with the --use-strict flag I get the following error:

    /Users/xxx/yyy/node_modules/xpath/xpath.js:3283
    Functions = new Object();
              ^
    ReferenceError: Functions is not defined
        at /Users/xxx/yyy/node_modules/xpath/xpath.js:3283:11
        at Object.<anonymous> (/Users/xxx/yyy/node_modules/xpath/xpath.js:4339:3)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
    ....

**Comment by atomantic** [comment]
same thing. Disabling strict mode fixes it.

**Comment by JLRishe** [comment]
Should be fixed in https://github.com/goto100/xpath/commit/34f1f0643a9755cff807d9dc199505622b4506cf
